export default [
    {
        "type": "CHECKBOX",
        "title": "Algemene Gegevens",
        "banner_url_full": "https://picsum.photos/seed/1461081139/800/400",
        "banner_url_small": "https://picsum.photos/seed/805389230/400/200",
        "pre_question_text": null,
        "question": "Wat is uw leeftijd?",
        "explanation": "Sunt mollitia cupiditate dolorem est iste. Iusto nobis et voluptas ratione impedit inventore. Distinctio ab corporis rerum vero accusantium et ea. Odit nostrum sit omnis eveniet blanditiis aut.",
        "post_question_text": "post question text will be showen here",
        "post_answer_banner_url_full": "https://picsum.photos/seed/1461081139/800/400",
        "post_answer_banner_url_small": "https://picsum.photos/seed/1461081139/400/200",
        "post_answer_text": "Sunt mollitia cupiditate dolorem est iste. Iusto nobis et voluptas ratione impedit inventore. Distinctio ab corporis rerum vero accusantium et ea. Odit nostrum sit omnis eveniet blanditiis aut.",
        "default_value": null,
        "mandatory": 1,
        "min": null,
        "min_errmsg": null,
        "max": null,
        "max_errmsg": null,
        "step": null,
        "digits": null,
        "digits_errmsg": null,
        "validator": null,
        "validator_errmsg": null,
        "min_answers": null,
        "min_answers_errmsg": null,
        "max_answers": null,
        "max_answers_errmsg": null,
        "tens_question_code": null,
        "index_number": 1,
        "questionnaire_id": 1,
        "question_id": 1,
        "next_question_id": 2,
        "name": "abtest",
        "number_of_questions": 6,
        "description": null,
        "answer": null,
        "answers": [
            {
                "code": "75",
                "text": "75",
                "icon_url": null,
                "icon_svg": null,
                "order": "61",
                "goto_item_id": null
            },
            // {
            //     "code": "21",
            //     "text": "21",
            //     "icon_url": null,
            //     "icon_svg": null,
            //     "order": "7",
            //     "goto_item_id": null
            // },
            {
                "code": "22",
                "text": "22",
                "icon_url": null,
                "icon_svg": null,
                "order": "8",
                "goto_item_id": null
            },
            {
                "code": "23",
                "text": "23",
                "icon_url": null,
                "icon_svg": null,
                "order": "9",
                "goto_item_id": null
            }
        ],
        "error_msg": null
    },
    {
        "type": "NUMBER",
        "title": "Algemene Gegevens",
        "banner_url_full": "https://picsum.photos/seed/48669189/800/400",
        "banner_url_small": "https://picsum.photos/seed/176883398/400/200",
        "pre_question_text": null,
        "question": "Wat is uw geslacht?",
        "explanation": null,
        "post_question_text": null,
        "post_answer_banner_url_full": null,
        "post_answer_banner_url_small": null,
        "post_answer_text": null,
        "default_value": null,
        "mandatory": 0,
        "min": null,
        "min_errmsg": null,
        "max": null,
        "max_errmsg": null,
        "step": null,
        "digits": null,
        "digits_errmsg": null,
        "validator": null,
        "validator_errmsg": null,
        "min_answers": null,
        "min_answers_errmsg": null,
        "max_answers": null,
        "max_answers_errmsg": null,
        "tens_question_code": null,
        "index_number": 2,
        "questionnaire_id": 1,
        "question_id": 2,
        "next_question_id": null,
        "name": "abtest",
        "number_of_questions": 6,
        "description": null,
        "answer": "15.0",
        "answers": null,
        "error_msg": null
    },
    {
        "type": "RADIO",
        "title": "Algemene Gegevens",
        "banner_url_full": "https://picsum.photos/seed/48669189/800/400",
        "banner_url_small": "https://picsum.photos/seed/176883398/400/200",
        "pre_question_text": null,
        "question": "Wat is uw geslacht?",
        "explanation": null,
        "post_question_text": null,
        "post_answer_banner_url_full": null,
        "post_answer_banner_url_small": null,
        "post_answer_text": null,
        "default_value": null,
        "mandatory": 0,
        "min": null,
        "min_errmsg": null,
        "max": null,
        "max_errmsg": null,
        "step": null,
        "digits": null,
        "digits_errmsg": null,
        "validator": null,
        "validator_errmsg": null,
        "min_answers": null,
        "min_answers_errmsg": null,
        "max_answers": null,
        "max_answers_errmsg": null,
        "tens_question_code": null,
        "index_number": 3,
        "questionnaire_id": 1,
        "question_id": 3,
        "next_question_id": 4,
        "name": "abtest",
        "number_of_questions": 6,
        "description": null,
        "answer": "15.0",
        "answers": [
            {
                "code": "1",
                "text": "man",
                "icon_url": null,
                "icon_svg": null,
                "order": "1",
                "goto_item_id": null
            },
            {
                "code": "2",
                "text": "vrouw",
                "icon_url": null,
                "icon_svg": null,
                "order": "2",
                "goto_item_id": null
            },
            {
                "code": "3",
                "text": "onbepaald",
                "icon_url": null,
                "icon_svg": null,
                "order": "3",
                "goto_item_id": null
            }
        ],
        "error_msg": null
    },
    {
        "type": "DROPDOWN",
        "title": "Algemene Gegevens",
        "banner_url_full": "https://picsum.photos/seed/48669189/800/400",
        "banner_url_small": "https://picsum.photos/seed/176883398/400/200",
        "pre_question_text": null,
        "question": "Wat is uw geslacht?",
        "explanation": null,
        "post_question_text": null,
        "post_answer_banner_url_full": "https://picsum.photos/seed/1461081139/800/400",
        "post_answer_banner_url_small": "https://picsum.photos/seed/1461081139/400/200",
        "post_answer_text": "Sunt mollitia cupiditate dolorem est iste. Iusto nobis et voluptas ratione impedit inventore. Distinctio ab corporis rerum vero accusantium et ea. Odit nostrum sit omnis eveniet blanditiis aut.",
        "default_value": null,
        "mandatory": 0,
        "min": null,
        "min_errmsg": null,
        "max": null,
        "max_errmsg": null,
        "step": null,
        "digits": null,
        "digits_errmsg": null,
        "validator": null,
        "validator_errmsg": null,
        "min_answers": null,
        "min_answers_errmsg": null,
        "max_answers": null,
        "max_answers_errmsg": null,
        "tens_question_code": null,
        "index_number": 4,
        "questionnaire_id": 1,
        "question_id": 4,
        "next_question_id": 5,
        "name": "abtest",
        "number_of_questions": 6,
        "description": null,
        "answer": "15.0",
        "answers": [
            {
                "code": "1",
                "text": "man",
                "icon_url": null,
                "icon_svg": null,
                "order": "1",
                "goto_item_id": null
            },
            {
                "code": "2",
                "text": "vrouw",
                "icon_url": null,
                "icon_svg": null,
                "order": "2",
                "goto_item_id": null
            },
            {
                "code": "3",
                "text": "onbepaald",
                "icon_url": null,
                "icon_svg": null,
                "order": "3",
                "goto_item_id": null
            }
        ],
        "error_msg": null
    },
    {
        "type": "TEXT",
        "title": "Algemene Gegevens",
        "banner_url_full": "https://picsum.photos/seed/48669189/800/400",
        "banner_url_small": "https://picsum.photos/seed/176883398/400/200",
        "pre_question_text": null,
        "question": "Wat is uw geslacht?",
        "explanation": null,
        "post_question_text": null,
        "post_answer_banner_url_full": null,
        "post_answer_banner_url_small": null,
        "post_answer_text": null,
        "default_value": null,
        "mandatory": 0,
        "min": null,
        "min_errmsg": null,
        "max": null,
        "max_errmsg": null,
        "step": null,
        "digits": null,
        "digits_errmsg": null,
        "validator": null,
        "validator_errmsg": null,
        "min_answers": null,
        "min_answers_errmsg": null,
        "max_answers": null,
        "max_answers_errmsg": null,
        "tens_question_code": null,
        "index_number": 5,
        "questionnaire_id": 1,
        "question_id": 5,
        "next_question_id": 6,
        "name": "abtest",
        "number_of_questions": 6,
        "description": null,
        "answer": "15.0",
        "answers": null,
        "error_msg": null
    },
    {
        "type": "BOOLEAN",
        "title": "Algemene Gegevens",
        "banner_url_full": "https://picsum.photos/seed/48669189/800/400",
        "banner_url_small": "https://picsum.photos/seed/176883398/400/200",
        "pre_question_text": null,
        "question": "Wat is uw geslacht?",
        "explanation": null,
        "post_question_text": null,
        "post_answer_banner_url_full": null,
        "post_answer_banner_url_small": null,
        "post_answer_text": null,
        "default_value": null,
        "mandatory": 0,
        "min": null,
        "min_errmsg": null,
        "max": null,
        "max_errmsg": null,
        "step": null,
        "digits": null,
        "digits_errmsg": null,
        "validator": null,
        "validator_errmsg": null,
        "min_answers": null,
        "min_answers_errmsg": null,
        "max_answers": null,
        "max_answers_errmsg": null,
        "tens_question_code": null,
        "index_number": 6,
        "questionnaire_id": 1,
        "question_id": 6,
        "next_question_id": null,
        "name": "abtest",
        "number_of_questions": 6,
        "description": null,
        "answer": "15.0",
        "answers": null,
        "error_msg": null
    },
]